CREATE SCHEMA IF NOT EXISTS `Nacritech` DEFAULT CHARACTER SET latin1 ;
USE `Nacritech` ;

CREATE TABLE IF NOT EXISTS `Nacritech`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50)NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `cedula` VARCHAR(10) NULL DEFAULT NULL,
  `servicio` VARCHAR(20) NULL DEFAULT NULL,
  `comentario` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;
